FROM nvidia/cuda:12.6.3-cudnn-devel-ubuntu22.04

USER root

RUN apt update
RUN apt install -y python3 python3-pip python3-dev

RUN pip install numpy torch jupyterlab

COPY cert.pem key.pem /home/jovyan/work/
COPY jupyter_lab_config.py /home/jovyan/.jupyter/

EXPOSE 8888

CMD ["jupyter", "lab"]
